examen2/apiexamen/urls.py
from django.urls import path
from . import views
app_name = "api"

urlpatterns = [
    path('users/list', views.UserListAPIView.as_view(), name='user_list'),
    path('employees/', views.EmployeesListView.as_view(), name='employee_list'),
    path('create/employee/', views.CreateEmployeeAPIView.as_view(), name='employee_create'),
    path('tasks/', views.TaskListView.as_view(), name='task_list'),
    path('tasks/ids/', views.TaskListIDSView.as_view(), name='task_list_ids'),
    path('tasks/list/title/', views.TaskListTitleView.as_view(), name='task_list_title'),
    path('tasks/pending/', views.TaskPending.as_view(), name='task_pending'),
    path('tasks/completed/', views.TaskCompleted.as_view(), name='task_pending'),
    path('tasks/users/ids/', views.TaskUserListIDSView.as_view(), name='task_list_ids'),
    path('tasks/users/pending/', views.TaskUserPending.as_view(), name='task_list_pending'),
    path('tasks/users/completed/', views.TaskUserCompleted.as_view(), name='task_list_completed'),
    path('tasks/create', views.CreateTaskAPIView.as_view(), name='task_list_create'),
    # path('tasks/<int:pk>/', views.TaskRetrieveUpdateDestroy.as_view(), name='task_retrieve_update_destroy'),
]

examen2/clientExamen/clientExamen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('examen/', include('front.urls')),
]

examen2/clientExamen/front/urls.py
from django.urls import path
from . import views

app_name = "emp"

urlpatterns = [
    path('employee/list', views.ListEmployeesClient.as_view(), name="list_employee"),
    path('employee/create', views.EmployeeCreate.as_view(), name="create_employee"),
    path('task/list', views.ListTaskClient.as_view(), name="list_task"),
    path('task/list/ids', views.TasksIDS.as_view(), name="list_taskid"),
    path('task/list/title', views.TaskTitles.as_view(), name="list_tasktitle"),
    path('task/pending', views.TaskPending.as_view(), name="list_taskpending"),
    path('task/completed', views.TaskCompleted.as_view(), name="list_taskcompleted"),
    path('task/user/id', views.TasksUSERSIDS.as_view(), name="list_taskuserids"),
    path('task/user/pending', views.TasksUserPending.as_view(), name="list_taskuserpending"),
    path('task/user/completed', views.TaskUserCompleted.as_view(), name="list_completedUser"),
    path('task/create', views.TaskCreate.as_view(), name="task_create"),
]

examen2/examenback/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # URL for the API
    path('api/', include('apiexamen.urls')),
]

examen2/clientExamen/front/models.py
from django.db import models

# Create your models here.

examen2/clientExamen/front/forms.py
# forms.py
from django import forms
from django.forms.widgets import DateInput
import requests

class CreateEmployeeForm(forms.Form):
    name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Escribe el name!"}))
    last_name = forms.CharField(max_length=32, widget=forms.Textarea(attrs={"type": "text", "class": "form-control", "placeholder": "Escribe tu apellido!"}))
    email = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type": "text", "class": "form-control"}))
    phone = forms.CharField(max_length=10, widget=forms.TextInput(attrs={"type": "text", "class": "form-control"}))
    address = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"type": "text", "class": "form-control"}))
    created = forms.DateField(widget=DateInput(attrs={"type": "date", "class": "form-control"}))
    updated = forms.DateField(widget=DateInput(attrs={"type": "date", "class": "form-control"}))
    user = forms.ChoiceField(choices=[])
    def __init__(self, *args, **kwargs):
        super(CreateEmployeeForm, self).__init__(*args, **kwargs)
        self.fields['user'].choices = self.get_user_choices()

    def get_user_choices(self):
        try:
            api_url = 'http://127.0.0.1:8000/api/users/list'  # Actualiza con la URL correcta de tu API
            response = requests.get(api_url)

            if response.status_code == 200:
                users = response.json()
                choices = [(user['id'], user['username']) for user in users]
                return choices
            else:
                return []  # Devolver una lista vacía en caso de que la solicitud falle o no devuelva datos

        except requests.exceptions.RequestException as e:
            print(f'Error en la solicitud HTTP: {e}')
            return []  # Manejar la ex


class CreateTaskForm(forms.Form):
    name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Escribe el name!"}))
    description = forms.CharField(max_length=32, widget=forms.Textarea(attrs={"type": "text", "class": "form-control", "rows": 3, "placeholder": "Escribe la description!"}))
    created = forms.DateField(widget=DateInput(attrs={"type": "date", "class": "form-control"}))
    due_date = forms.DateField(widget=DateInput(attrs={"type": "date", "class": "form-control"}))
    state = forms.ChoiceField(choices=[("PENDING", "PENDING"), ("IN_PROGRESS", "IN_PROGRESS"), ("COMPLETED", "COMPLETED")])
    employee = forms.ChoiceField(choices=[])

    def __init__(self, *args, **kwargs):
        super(CreateTaskForm, self).__init__(*args, **kwargs)
        self.fields['employee'].choices = self.get_employee_choices()

    def get_employee_choices(self):
        try:
            api_url = 'http://localhost:8000/api/employees/'  # Actualiza con la URL correcta de tu API de empleados
            response = requests.get(api_url)

            if response.status_code == 200:
                employees = response.json()
                choices = [(employee['id'], employee['name']) for employee in employees]
                return choices
            else:
                return []  # Devolver una lista vacía en caso de que la solicitud falle o no devuelva datos

        except requests.exceptions.RequestException as e:
            print(f'Error en la solicitud HTTP: {e}')
            return [] 

examen2/clientExamen/front/views.py
from django.shortcuts import render, redirect
from django.views import generic
import requests
from .forms import CreateEmployeeForm, CreateTaskForm
CreateTaskForm
class EmployeeCreate(generic.View):
    template_name = "front/create_employee.html"
    context = {}
    payload = {}
    url = "http://127.0.0.1:8000/api/create/employee/"
    response = None
    form_class = CreateEmployeeForm
    def get(self, request):
        self.context = {
            "form": self.form_class,
        }
        return render(request, self.template_name, self.context)

    def post(self, request):
        self.payload = {
                "user": request.POST.get("user"),
                "name":request.POST.get("name"),
                "last_name": request.POST.get("last_name"),
                "email": request.POST.get("email"),
                "phone": request.POST.get("phone"),
                "address": request.POST.get("address"),
                "created": request.POST.get("created"),
                "updated": request.POST.get("updated"),
        }
        self.response = requests.post(url=self.url, data=self.payload)
        return redirect("emp:list_employee")

class TaskCreate(generic.View):
    template_name = "front/create_tasks.html"
    context = {}
    payload = {}
    url = "http://127.0.0.1:8000/api/tasks/create"
    response = None
    form_class = CreateTaskForm
    def get(self, request):
        self.context = {
            "form": self.form_class,
        }
        return render(request, self.template_name, self.context)

    def post(self, request):
        self.payload = {
                "name":request.POST.get("name"),
                "description": request.POST.get("description"),
                "created": request.POST.get("created"),
                "due_date": request.POST.get("due_date"),
                "state": request.POST.get("state"),
                "employee": request.POST.get("employee"),
        }
        self.response = requests.post(url=self.url, data=self.payload)
        return redirect("emp:list_task")



# Create your views here.
class ListEmployeesClient(generic.View):
    template_name = "front/list_employee.html"
    url = "http://127.0.0.1:8000/api/employees/"
    response = None
    context= {}
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "employees": self.response.json(),
        }
        return render(request, self.template_name, self.context)

class ListTaskClient(generic.View):
    template_name = "front/list_task.html"
    url = "http://127.0.0.1:8000/api/tasks/"
    response = None
    context= {}
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "tasks": self.response.json(),
        }
        return render(request, self.template_name, self.context)

class TasksIDS(generic.View):
    template_name = "front/list_taskid.html"
    url = "http://127.0.0.1:8000/api/tasks/ids/"
    response = None
    context= {}
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "tasks": self.response.json(),
        }
        return render(request, self.template_name, self.context)

class TaskTitles(generic.View):
    template_name = "front/list_task_title.html"
    url = "http://127.0.0.1:8000/api/tasks/list/title/"
    response = None
    context= {}
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "tasks": self.response.json(),
        }
        return render(request, self.template_name, self.context)

class TaskPending(generic.View):
    template_name = "front/list_task_pending.html"
    url = "http://127.0.0.1:8000/api/tasks/pending/"
    response = None
    context= {}
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "tasks": self.response.json(),
        }
        return render(request, self.template_name, self.context)

class TaskCompleted(generic.View):
    template_name = "front/list_task_completed.html"
    url = "http://127.0.0.1:8000/api/tasks/completed/"
    response = None
    context= {}
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "tasks": self.response.json(),
        }
        return render(request, self.template_name, self.context)

class TasksUSERSIDS(generic.View):
    template_name = "front/list_task_userid.html"
    url = "http://127.0.0.1:8000/api/tasks/users/ids/"
    response = None
    context= {}
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "tasks": self.response.json(),
        }
        return render(request, self.template_name, self.context)
    
class TasksUserPending(generic.View):
    template_name = "front/list_task_user_pending.html"
    url = "http://127.0.0.1:8000/api/tasks/users/pending/"
    response = None
    context= {}
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "tasks": self.response.json(),
        }
        return render(request, self.template_name, self.context)
class TaskUserCompleted(generic.View):
    template_name = "front/list_task_user_completed.html"
    url = "http://127.0.0.1:8000/api/tasks/users/completed/"
    response = None
    context= {}
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "tasks": self.response.json(),
        }
        return render(request, self.template_name, self.context)

examen2/clientExamen/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    <div class="row">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Examen2do</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'emp:list_employee' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Employees Actions
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'emp:list_employee' %}">Employees List</a></li>
                  <li><a class="dropdown-item" href="{% url 'emp:create_employee' %}">New Employee</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Tasks Actions
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'emp:list_task' %}">Task List</a></li>
                  <li><a class="dropdown-item" href="{% url 'emp:list_taskid' %}">Task List ID</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'emp:list_tasktitle' %}">Task LIst Ttile</a></li>
                  <li><a class="dropdown-item" href="{% url 'emp:list_taskpending' %}">Task LIst Pending</a></li>
                  <li><a class="dropdown-item" href="{% url 'emp:list_taskcompleted' %}">Task LIst Completed</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'emp:list_taskuserids' %}">Task/user ID</a></li>
                  <li><a class="dropdown-item" href="{% url 'emp:list_taskuserpending' %}">Task/user LIst Pending</a></li>
                  <li><a class="dropdown-item" href="{% url 'emp:list_completedUser' %}">Task/user LIst Completed</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'emp:task_create' %}">New Task</a></li>
                </ul>
              </li>
             
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <hr>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          {% block content %}
          {% endblock content %}
        </div>
        <div class="col-2"></div>
    </div>
    <hr>
    <div class="row">
          <footer class="bg-body-tertiary text-center text-lg-start">
            <!-- Grid container -->
            <div class="container p-4">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                  <h5 class="text-uppercase">Footer text</h5>
          
                  <p>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                    molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
                    voluptatem veniam, est atque cumque eum delectus sint!
                  </p>
                </div>
                <!--Grid column-->
          
                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                  <h5 class="text-uppercase">Footer text</h5>
          
                  <p>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                    molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
                    voluptatem veniam, est atque cumque eum delectus sint!
                  </p>
                </div>
                <!--Grid column-->
              </div>
              <!--Grid row-->
            </div>
            <!-- Grid container -->
          
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
              © 2020 Copyright:
              <a class="text-body" href="https://mdbootstrap.com/">MDBootstrap.com</a>
            </div>
            <!-- Copyright -->
          </footer>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>